name: PRE-Release Server
on:
  push:
    tags: "Server-*"

jobs:
  build:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: |
          vers=${GITHUB_REF#refs/tags/Server-}
          vers=${vers/rc}
          dotnet build --configuration Release  /p:AssemblyVersion=$vers
      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Publish Server
        run: dotnet publish --no-build ./MyNoSqlGrpc.Server/MyNoSqlGrpc.Server.csproj --output ./publish-api --configuration Release

      - name: ls
        run: ls ./publish-api

      - name: Publish Server to Registry
        uses: swisschain/Publish-Docker-Github-Action@master
        with:
          name: myjettools/my-nosql-gprc-server-beta
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./publish-api
          # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
          tag_names: true
          tag_name_skip: Server-
